#!/bin/bash
OUT="/tmp/enum_$$.txt"
echo "=== RPM packages ===" > "$OUT"
rpm -qa --qf '%{NAME}-%{VERSION}\n' 2>/dev/null | sort >> "$OUT"
echo -e "\n=== SUID ===" >> "$OUT"
find / -perm -4000 -type f -exec ls -la {} + 2>/dev/null >> "$OUT"
echo -e "\n=== SGID ===" >> "$OUT"
find / -perm -2000 -type f -exec ls -la {} + 2>/dev/null >> "$OUT"
echo -e "\n=== File caps ===" >> "$OUT"
getcap -r / 2>/dev/null >> "$OUT"
echo -e "\n=== Services ===" >> "$OUT"
systemctl list-units --type=service --state=running --no-pager 2>/dev/null >> "$OUT"
echo -e "\n=== Timers ===" >> "$OUT"
systemctl list-timers --all --no-pager 2>/dev/null >> "$OUT"
echo -e "\n=== Cron ===" >> "$OUT"
ls -la /etc/cron.d/ /etc/cron.daily/ /etc/cron.hourly/ /var/spool/cron/ 2>/dev/null >> "$OUT"
cat /etc/cron.d/* /var/spool/cron/* 2>/dev/null >> "$OUT"
echo -e "\n=== Ports ===" >> "$OUT"
ss -tlnp 2>/dev/null >> "$OUT"
echo -e "\n=== Sudo ===" >> "$OUT"
sudo -l 2>/dev/null >> "$OUT"
echo -e "\n=== Writable /etc ===" >> "$OUT"
find /etc -writable 2>/dev/null >> "$OUT"
echo -e "\n=== World-writable dirs ===" >> "$OUT"
find / -maxdepth 3 -writable -type d ! -path '/proc/*' ! -path '/sys/*' ! -path '/tmp/*' ! -path '/dev/*' ! -path '/run/*' 2>/dev/null >> "$OUT"
echo -e "\n=== /opt /usr/local ===" >> "$OUT"
ls -laR /opt/ /usr/local/bin/ /usr/local/sbin/ 2>/dev/null >> "$OUT"
echo -e "\n=== Kernel modules ===" >> "$OUT"
lsmod 2>/dev/null >> "$OUT"
echo -e "\n=== Env ===" >> "$OUT"
env 2>/dev/null >> "$OUT"
echo "Done -> $OUT"
cat "$OUT"
